<?php

namespace App\Packages\Services\Sites\Framework\WordPress;

use App\Models\ServerSite;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

/**
 * Generates wp-config.php content for WordPress installations.
 */
class WordPressConfigGenerator
{
    /**
     * Generate wp-config.php content for a WordPress site.
     */
    public function generate(ServerSite $site): string
    {
        $database = $site->database;
        $protocol = $site->ssl_enabled ? 'https' : 'http';
        $siteUrl = "{$protocol}://{$site->domain}";

        // Get WordPress security salts
        $salts = $this->generateSalts();

        // Escape single quotes in password
        $password = addslashes($database->root_password);

        return <<<PHP
<?php
/**
 * WordPress Configuration File
 *
 * Generated by BrokeForge
 * Site: {$site->domain}
 */

// Database Configuration
define('DB_NAME', '{$database->name}');
define('DB_USER', 'root');
define('DB_PASSWORD', '{$password}');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

// Authentication Unique Keys and Salts
{$salts}

// WordPress Database Table Prefix
\$table_prefix = 'wp_';

// Site URL Configuration
define('WP_HOME', '{$siteUrl}');
define('WP_SITEURL', '{$siteUrl}');

// Debugging
define('WP_DEBUG', false);

// Absolute path to the WordPress directory
if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

// Sets up WordPress vars and included files
require_once ABSPATH . 'wp-settings.php';
PHP;
    }

    /**
     * Generate or fetch WordPress security salts.
     */
    protected function generateSalts(): string
    {
        // Try to fetch from WordPress.org API
        try {
            $response = Http::timeout(5)->get('https://api.wordpress.org/secret-key/1.1/salt/');

            if ($response->successful() && ! empty($response->body())) {
                return trim($response->body());
            }
        } catch (\Exception $e) {
            // Fall back to generating our own salts if API fails
        }

        // Generate salts locally if API fails
        return $this->generateLocalSalts();
    }

    /**
     * Generate WordPress salts locally.
     */
    protected function generateLocalSalts(): string
    {
        $keys = [
            'AUTH_KEY',
            'SECURE_AUTH_KEY',
            'LOGGED_IN_KEY',
            'NONCE_KEY',
            'AUTH_SALT',
            'SECURE_AUTH_SALT',
            'LOGGED_IN_SALT',
            'NONCE_SALT',
        ];

        $salts = [];

        foreach ($keys as $key) {
            $salt = Str::random(64);
            $salts[] = "define('{$key}', '{$salt}');";
        }

        return implode("\n", $salts);
    }
}
